num1 = input("Enter number one value : ")
num2 = input("Enter number two value : ")
# num1 = int(input("Enter number one value : "))
# num2 = int(input("Enter number two value : "))
print("num1,num2 : "+num1,num2)
print("num1+num2 : "+num1+num2)
num1 = int(num1)
num2 = int(num2)
print("num1+num2 : ",num1+num2)